version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - html-data:/usr/share/nginx/html
      - nginx-logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  html-data:
  nginx-logs:

